apiVersion: v1
kind: Pod
metadata:
  name: exemplo-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html   # Caminho onde o volume será montado
          name: exemplo-volume
  volumes:
    - name: exemplo-volume
      persistentVolumeClaim:
        claimName: exemplo-pvc   # Nome do PVC que será utilizado
